# Generated by Django 3.2.7 on 2021-09-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20210912_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carcomment',
            name='rating',
        ),
        migrations.AlterField(
            model_name='car',
            name='currency',
            field=models.CharField(choices=[('usd', 'usd'), ('som', 'сом')], default='usd', max_length=24),
        ),
    ]
